library(shiny)
library(shinydashboard)
library(tidyverse)
library(lubridate)
library(scales)
library(echarts4r)
library(highcharter)
library(htmlwidgets)
library(magrittr)
library(glue)
library(hwordcloud)
library(formattable)
library(DT)

profiles <- readRDS("data/profiles.rds")
ig_posts <- readRDS("data/ig_posts.rds")
data <- readRDS("data/data.rds")
profiles_linkedin <- readRDS("data/profiles_linkedin.rds")
profiles_facebook <- readRDS("data/profiles_facebook.rds")
profiles_youtube <- readRDS("data/profiles_youtube.rds")
profiles_twitter <- readRDS("data/profiles_twitter.rds")
tweets <- readRDS("data/tweets.rds")

news <- readRDS("data/news.rds")
news2 <- readRDS("data/news2.rds")

source("ui.R")
source("server.R")
shinyApp(ui, server)